home-url=https://crosspaste.com
change-log-url=https://github.com/clownfishrob/crosspaste-desktop/blob/pasteflow-dev-mvp/app/src/desktopMain/resources/whats-new/en.md
check-metadata-url=
version-api-url=
issue-tracker-url=https://github.com/clownfishrob/crosspaste-desktop/issues
