home-url=https://github.com/clownfishrob/crosspaste-desktop
change-log-url=https://github.com/clownfishrob/crosspaste-desktop/blob/pasteflow-dev-mvp/app/src/desktopMain/resources/whats-new/en.md
check-metadata-url=https://raw.githubusercontent.com/clownfishrob/crosspaste-desktop/pasteflow-dev-mvp/docs/update/metadata.properties
version-api-url=
issue-tracker-url=https://github.com/clownfishrob/crosspaste-desktop/issues
